CREATE DATABASE Store;

USE Store;

-- THIS COMMAND CREATES TABLE
-- IT DEFINES THE DATABASE MEANING IT DEFINES DATA TYPES OF THE ATTRIBUTES AND
-- CONTRAINTS THAT MUST BE MET BY THE ENTITY OR BY THE TABLE
CREATE TABLE Customers (
    CustomerID INT IDENTITY(1, 1),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    City VARCHAR(50) NOT NULL,
    PRIMARY KEY (CustomerID)
);

-- THIS IS THE SECOND TABLE WHICH IS THE CHILD OF THE CUSTOMER TABLE
-- THIS TABLE IS GOING HAVE A NEW KEY TYPE WHICH IS FOREIGN KEY THAT REFERENCES TO CUSTOMER TABLE,
-- REFERENCING USING CUSTOMERID THAT IS IN THE CUSTOMER TABLE
-- THIS TABLE MUST HAVE A ATTRIBUTE THAT IS GOING TO STORE THE PRIMARY KEY ITS PARENT WHICH IS THE CUSTOMER ID
CREATE TABLE Orders (
    OrdersID INT IDENTITY(1, 1),
    CustomerID INT NOT NULL,
    OrderDate DATE NOT NULL,
    OrderPrice DECIMAL(10 ,2),
    FOREIGN KEY (CustomerID) REFERENCES Customers (CustomerID)
);

ALTER TABLE Orders
ADD PRIMARY KEY (OrdersID);

CREATE TABLE Orders_Items (
    Order_Item_ID INT IDENTITY(1, 1) PRIMARY KEY,
    Order_ID INT NOT NULL,
    Order_Date DATE NOT NULL,
    FOREIGN KEY (Order_ID) REFERENCES Orders (OrdersID)
);

ALTER TABLE Orders_Items
ADD Item_ID INT NOT NULL;

ALTER TABLE Orders_Items
ADD Quantity INT NOT NULL CHECK (Quantity > 0);

ALTER TABLE Orders_Items
ADD Unit_Price DECIMAL(10 ,2) NOT NULL;
