name: SQL Linting CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python (SQLFluff requires Python)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install SQLFluff
      - name: Install SQLFluff
        run: |
          pip install sqlfluff

      # Run SQLFluff to lint SQL files (in T-SQL dialect)
      - name: Lint SQL files
        run: |
          sqlfluff lint "**/*.sql" --dialect tsql
