name: SQL Linting CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install SQLFluff
        run: |
          pip install sqlfluff

      - name: Lint SQL files in root directory
        run: |
          sqlfluff lint --dialect=tsql *.sql
